### ISSUE TITLE
Simplify getting Coordinates from Joints

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1066]
### TODO
- [x] Improve interface for accessing Coordinates (PR #1116)
- [x] Replace CoordinateSet with a list property (PR #1210)
- [x] Add `updCoordinate()` methods (analogous to `getCoordinate()`) (PR #1222)
- [x] Replace `getCoordinateSet()[#]` with `getCoordinate(enum)` (or `updCoordinate(enum)`) (PR #1222)

-----

We currently need to get the entire `CoordinateSet` from a Joint:
```cpp
reporter->updInput("inputs").connect(myJoint->getCoordinateSet()[0].getOutput("value"));
```
It would look cleaner if we could replace the `()[0]` with just `(0)`:
```cpp
reporter->updInput("inputs").connect(myJoint->getCoordinate(0).getOutput("value"));
// or
reporter->updInput("inputs").connect(myJoint->getCoordinate("kneeFlexion").getOutput("value"));
```

**Comment by aseth1** [comment]
This could be done pretty easily if we did not use the Set but use a property list of `<coordinates>`; then it would be `get_coordinates(0)`. I was thinking of doing that at some point.

**Comment by tkuchida** [comment]
Ok, I'll look into this. I would also like to do
```cpp
myPinJoint.getCoordinate();
```
if there is only one Coordinate (e.g., `double getCoordinate(int idx = -1) const;` and return `get_coordinates(0)` if the list is of length 1.

**Comment by tkuchida** [comment]
We could also introduce enums to improve readability, e.g.
```cpp
myFreeJoint.getCoordinate(FreeJoint::rotation1);
```

**Comment by aymanhab** [comment]
Perfect, thanks @tkuchida :+1:

**Comment by chrisdembia** [comment]
Most alternatives would be better than what we have now.

**Comment by tkuchida** [comment]
Fixed by PRs #1116, #1210, and #1222.
