### ISSUE TITLE
Steps to convert hopper device example to MATLAB

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1504]
In converting the Hopper Device example to MATLAB, there are a few steps to take with the C++ libraries:

- [x] Move SignalGenerator to osimCommon
- [x] Create a new library called "osimExampleComponents" or "osimExampleClasses" and put PropMyoController and Device here.
- [x] SWIG bindings for SimTK::Visualizer.
- [x] Move Tom's showSubcomponentInfo() to Component::dumpSubcomponentInfo(); similar for outputs and inputs (and allow options for showing "just mine" or "for all descendants").
