### ISSUE TITLE
Test and update examples for 4.0 release

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1697]
## API Examples (from #1297)
- [x] Script to build a template actuators (see PR #541 (Shrinidhi)
- [ ] Convert dynamic walker example (C++ @chrisdembia,  MATLAB @jimmyDunne)
- [x] Convert hopper example (Chris)
- [ ] Convert between Millard and Thelen muscle models  (Ayman)
- [x] Pendulum with markers; output marker locations (James)
- [x] Plot muscle curves (James)
- [x] Show how to use the DataTable's `flatten()` and pack() in scripting (James)
- [ ] Muscle analysis (@aseth1 and @carmichaelong)
- [ ] Point and body kinematics; also report Center of Mass (@aseth1 using OutputReporter)
- [ ] States trajectory for custom post-hoc analysis (maybe trapeziodal rule for integration, Chris) 
- [ ] Update old matlab and python examples (James)
- [x] Dump model's connections, inputs and outputs (done by @tkuchida added to Component)

## API Examples (not from #1297)
- [ ] Working with lists (Matlab/Python) #1465 
- [ ] Sample code for dealing with enums in Matlab #1456 

## API Examples (Confluence) 
- [ ] [Performing a Simulation ](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Performing+a+Simulation)
- [ ] [Creating your own Analysis](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Creating+Your+Own+Analysis)
- [ ] [Creating a Controller](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Creating+a+Controller)
- [ ] [Creating an Optimization](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Creating+an+Optimization)
- [ ] [Creating a Customized Actuator](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Creating+a+Customized+Actuator) @chrisdembia
- [ ] [Creating a Cusomized Muslce Model](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Creating+a+Customized+Muscle+Model)
- [ ] [Getting Started as a Developer](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Getting+Started+as+a+Developer) @chrisdembia https://github.com/opensim-org/opensim-core/issues/2072

## Application Examples (Confluence) 
Introductory
- [ ] [Tutorial 1 -Intro to Musculoskeletal Modeling](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Tutorial+1+-+Intro+to+Musculoskeletal+Modeling) @bspineda 
- [ ] [Tutorial 2 - Simulation and Analysis of a Tendon Transfer Surgery](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Tutorial+2+-+Simulation+and+Analysis+of+a+Tendon+Transfer+Surgery) @bspineda 
- [ ] [Tutorial 3 - Scaling, Inverse Kinematics, and Inverse Dynamics](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Tutorial+3+-+Scaling%2C+Inverse+Kinematics%2C+and+Inverse+Dynamics)  @bspineda 
- [ ] [Simulation-Based Design to Prevent Ankle Injuries](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Simulation-Based+Design+to+Prevent+Ankle+Injuries) @nickbianco 
- [ ] [Simulation-Based Design to Reduce Metabolic Cost](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Simulation-Based+Design+to+Reduce+Metabolic+Cost) @nickbianco 
- [ ] [Dynamic Walking Challenge:Go the Distance](https://simtk-confluence.stanford.edu/pages/viewpage.action?pageId=24379457)
- [ ] [Working with Static Optimization](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Working+with+Static+Optimization)
- [ ] [Soccer Kick example](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Soccer+Kick+Example)

Intermediate
- [ ] [Computed Muscle Control](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Example+-+Computed+Muscle+Control)
- [ ] [Strength of Simulation: Estimating Leg Muscle Forces in Stance and Swing](https://simtk-confluence.stanford.edu/display/OpenSim/__40__The+Strength+of+Simulation%3A+Estimating+Leg+Muscle+Forces+in+Stance+and+Swing) @tkuchida
- [ ] [Joint Reaction Loads](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Example+-+Estimating+Joint+Reaction+Loads)
- [ ] [Model Editing](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Example+-+Model+Editing)

Advanced
- [ ] [Point Kinematics Example](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Point+Kinematics+Example) redundant with OuputrReporter- update to use OutputReporter
- [ ] [Pulling out the stops: Designing a muscle for tug-of-war competition](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Pulling+Out+the+Stops%3A+Designing+a+Muscle+for+a+Tug-of-War+Competition)
- [ ] [Sky High: Coordinating Muscles for Optimal Jump Performance](https://simtk-confluence.stanford.edu/display/OpenSim/__40__Sky+High%3A+Coordinating+Muscles+for+Optimal+Jump+Performance)  (replace `AnalyzeTool` with `ForwardTool` in Part C; see #1675)
- [ ] [From the Ground Up: Building a Passive Dynamic Model](https://simtk-confluence.stanford.edu/display/OpenSim/__40__From+the+Ground+Up%3A+Building+a+Passive+Dynamic+Walker+Model) @chrisdembia

## Wish List 
- [ ] Building custom joints (Examples of building basic and complicated joints. May include the building and complicated knee and/or shoulder)
- [ ] Rajagopal Model example - Build an example or a pipeline to showcase the model 
- [ ] Seth Shoulder model - Build an example or a pipeline to showcase the model 
- [ ] Muslce Synergy - example of a muscle synergy analysis
- [ ] Scaling - Going from model (without markers) to scaled and running IK (includes reading c3d)
- [ ] Evaluate model capacity - Evaluate joint toques and asses if muscles crossing the joint could generate the required forces
- [ ] Calculate cost of transport - 
- [ ] Document hopper example in a confluence page @nickbianco 
- [ ] Test GUI script for running tug of war in 485 @apoorvar 
- [ ] Extending a class (controller) in Python (Ayman)
- [ ] Optimization of standing balance movements with synergies (Mazen)

**Comment by tkuchida** [comment]
- [ ] MATLAB script for extracting muscle path points, including points on wrapping surfaces if possible.

**Comment by jenhicks** [comment]
Priorities: Existing examples
Examples demonstrating new software capabilities

**Comment by ShravanTata** [comment]
Hi,

Can we construct CustomJoints using the opensim4.0 Python API? I am having a lot of troubles doing it.
Any help is very much appreciated.

Thanks,
Shravan

**Comment by tkuchida** [comment]
@ShravanTata Yes, it is possible. Please see my response in [Forum topic 9738](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=9738). If you are still having difficulties, please provide more details (e.g., a small example of your code) on the Forum.

**Comment by jenhicks** [comment]
Closing, as this is duplicated and more up to date here: https://github.com/opensim-org/sprints/issues/17
