### ISSUE TITLE
Allow installing OpenSim-Core into UNIX /usr/ or /usr/local

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#195]
The number of unix users is increasing. The organization of our installation currently does not permit one to safely install into /usr/ or /usr/local. The following changes should occur:
- [x] On UNIX, do not copy over simbody libraries. #343 
- [x] Clean up CMake for api examples. #229
- [x] Clean up CMake for lepton. #327
- [x] Clean up "USING_NAMESPACE". #343 
- [x] Allow copying libraries to be an option. #343
- [ ] Create versioned libraries (SOVERSION), as is now done with Simbody.
- [x] Follow the [FHS](http://www.pathname.com/fhs/) filesystem hierarchy standard for the layout of the installation. This is facilitated by using CMake GNUInstallDirs. (gnu-install-dirs; chrisdembia:unix-install-2) #671
  - [x] configureOpenSim.m
  - [x] location of Java wrapping (look at vtk).
  - [x] location of python bindings (look at vtk). http://anonscm.debian.org/cgit/debian-science/packages/vtk6.git/tree/debian/python-vtk6.install, http://packages.ubuntu.com/trusty/amd64/python-vtk/filelist
- [x] Rename the executables so their names are distinguishable. Right now, e.g., linux already has an `id` executable, and our `id` would overwrite this. I suggest a single executable that takes a tool name as an argument, or renaming the executables as `opensim-ik`, and creating an `opensim` executable that calls `opensim-ik` when `opensim ik` is called (this is how command-line git works I think).

**Comment by chrisdembia** [comment]
Reminder to self: https://github.com/chrisdembia/opensim-core/tree/unix-install-2

**Comment by chrisdembia** [comment]
next branches to merge: unix-dont-copy-simbody and unix-install-2

**Comment by moorepants** [comment]
@chrisdembia just came across this: http://click.pocoo.org

I think it is setup to do command line interfaces with lots of nested subcommands. Same guy that wrote Flask wrote this, so it is likely good. There example implements the git subcommands:

http://click.pocoo.org/3/complex/#complex-guide

Maybe you can use it for Opensim's command line access (although you'd have to provide Python then).

**Comment by chrisdembia** [comment]
Awesome!! Thanks for sharing that. That's exactly what I was thinking about. Having to use python might be a serious limitation though.

**Comment by moorepants** [comment]
I'm not sure how Python is a limitation :)

You can embed a Python interpreter with the open sim app on Windows and just use the system python on other OS's.

**Comment by jimmyDunne** [comment]
>Rename the executables so their names are distinguishable. Right now, e.g., linux already has an id >executable, and our id would overwrite this. I suggest a single executable that takes a tool name as an >argument, or renaming the executables as opensim-ik, and creating an opensim executable that calls >opensim-ik when opensim ik is called (this is how command-line git works I think).

I just ran into this issue as well. Was struggling installing some python packages. The error isn't at first obvious because the exceptions are on tex-common/tex-live (font packages). 

I fixed by deleting the opensim id since I don't use it from command line

**Comment by chrisdembia** [comment]
It sounds like we'll move toward `opensim ik`, `opensim gui`, etc.

**Comment by sherm1** [comment]
> It sounds like we'll move toward opensim ik, opensim gui, etc.

I hope this won't conflict with [OpenSimulator](http://opensimulator.org/wiki/Main_Page)! I see they use `OpenSim.exe` and `OpenSim.ini` but I didn't see a command line `opensim`.

**Comment by tkuchida** [comment]
> I see they use OpenSim.exe and OpenSim.ini but I didn't see a command line opensim.

[OpenSim.exe Command Line Options](http://opensimulator.org/wiki/OpenSim.exe_Command_Line_Options)

**Comment by sherm1** [comment]
> OpenSim.exe Command Line Options

Oops! That's not good. I doubt we'll run into many users with both OpenSim and OpenSimulator (since they are totally unrelated) so we can probably just ignore that, but it is something to worry about. We could use `osim` instead, but `opensim` seems nicer.

**Comment by chrisdembia** [comment]
Thanks for those good finds. I'm okay with `osim`, though I agree that `opensim` is nicer. I think I'm okay with using `opensim` so long as popular package managers (apt-get, homebrew) don't install an OpenSimulator `opensim` or `OpenSim` executable into `/usr/` or `/usr/bin/`. My end goal with the `opensim` umbrella executable is to support getting opensim into apt-get.

OpenSimulator is not in the apt-get repositories nor in homebrew.

**Comment by sherm1** [comment]
> OpenSimulator is not in the apt-get repositories nor in homebrew.

We should get there first!

**Comment by aymanhab** [comment]
So, what does it take to get in?

**Comment by chrisdembia** [comment]
Most of the items are at the top. The two other items I'd add are:

1. prototyping debian package config files (we have great examples in Simbody's repo thanks to OSRF).
2. getting someone at Debian to evaluate our package.

Homebrew would be really easy though.

**Comment by jenhicks** [comment]
@aymanhab thoughts on the status of this one?
