### ISSUE TITLE
Intermediate PhysicalOffsetFrames will cause scaling failure for 5 Components

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1973]
Several Components point to a "parent" Frame, which was previously a Body but can now be a PhysicalOffsetFrame (and will almost always be a PhysicalOffsetFrame for Joints). Consequently, when searching through a ScaleSet for scale factors (by name), `getParentFrame().getName()` must now be `getParentFrame().findBaseFrame().getName()`. AFAIK this issue affects 5 Components:
- [GeometryPath](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/GeometryPath.cpp#L797)s whose ParentFrame is not a Body
- (Almost) all [EllipsoidJoint](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/EllipsoidJoint.cpp#L122)s (Joints are typically created using the 7-argument convenience constructor, which automatically creates PhysicalOffsetFrames)
- (Almost) all [CustomJoint](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/CustomJoint.cpp#L151)s (as above)
- Markers (via [MarkerSet](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/MarkerSet.cpp#L132)) that are mounted on PhysicalOffsetFrames
- [CoordinateCouplerConstraint](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimbodyEngine/CoordinateCouplerConstraint.cpp#L260)s connected to PhysicalOffsetFrames

### Tasks
- [x] Replace `getParentFrame()` with `getParentFrame().findBaseFrame()` in the 5 places linked above.

Improve coverage of testScale, which currently only checks the locations of markers mounted directly to bodies. Possible improvements:
- [x] mount some markers to PhysicalOffsetFrames
- [x] also check points on GeometryPaths
- [x] test with a model containing a GeometryPath whose ParentFrame is not a Body
- [x] test with a model containing an EllipsoidJoint, CustomJoint, and CoordinateCouplerConstraint

**Comment by tkuchida** [comment]
Should be fixed by PR #1994. Add tests to testScale to confirm.
