### ISSUE TITLE
Convert all tests to the `Catch2` framework

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3555]
Current testing in OpenSim uses a variety of implementations and code styles. Most of the tests for Moco use `Catch2`, and since the Moco merge, we've been sporadically converting OpenSim tests to this new framework. This epic proposes that we convert _all_ the OpenSim tests to `Catch2` to unify the testing suite, speed up development (i.e., isolating and re-running only failed tests), and make adding new tests easy. This should be a "many hands make light work" approach, where we divide up the tests to be converted across several individual issues that separate members of the dev team can tackle.

# Tasks

## ~~Phase 1: Convert existing code to minimally use Catch~~ (Done!)

- For each `.cpp` file in the list below:
  - `#include <catch2/catch_all.hpp>`
  - **Minimally** convert each test function to use `TEST_CASE("test name")`
  - Remove existing `main` function (`catch` automates calling each case)
  - Put helper functions in an anonymous namespace (`namespace {}`)
  - Check+commit - mention this issue (#3555) in the commit message if you want it to appear in GitHub
  - PR

## Phase 2: Update any build/contribution guides to mention the change

- [ ] Standardize how tests are added via `CMake` macros (if needed)
- [ ] Update `CONTRIBUTING.MD` with guidelines for writing `Catch2` tests (and links to `Catch2` docs)
- [ ] Decide if any changes needed for Java/Matlab/Python tests

## Phase 3: Improve assertions and test framework usage

- For each `cpp` file in the list below:

  - Update assertions to use catch assertions, instead of OpenSim/SimTK assertions (they provide better testing feedback)
  - Parameterize tests etc. where possible using catch's conventions
  - If other testing macros are necessary, consolidate them under `Auxiliary` or `Common` (i.e., remove `OpenSim/Moco/Test/Testing.h`

# Phase 1 CPP todo List

- [x] Actuators\
    - [x] Test\testActuators.cpp - #3684
    - [x] Test\testDeGrooteFregly2016Muscle.cpp
    - [x] Test\testModelProcessor.cpp
    - [x] Test\testMuscleFirstOrderActivationDynamicModel.cpp - #3691
    - [x] Test\testMuscleFixedWidthPennationModel.cpp
    - [x] Test\testMuscles.cpp
    - [x] Test\testSerializableMuscleCurves.cpp
- [x] Analyses\
    - [x] Test\testOutputReporter.cpp
- [x] Common\ - (@adamkewley : I'll start with this one)
    - [x] Test\testAPDMDataReader.cpp
    - [x] Test\testAssertion.cpp
    - [x] Test\testC3DFileAdapter.cpp (https://github.com/opensim-org/opensim-core/pull/4207)
    - [x] Test\testComponentInterface.cpp
    - [x] Test\testDataTable.cpp
    - [x] Test\testFunctionAdapter.cpp
    - [x] Test\testFunctions.cpp
    - [x] Test\testGCVSpline.cpp
    - [x] Test\testLatinHypercubeDesign.cpp
    - [x] Test\testMarkerData.cpp
    - [x] Test\testNCSpline.cpp
    - [x] Test\testPath.cpp
    - [x] Test\testRootSolver.cpp
    - [x] Test\testSerialization.cpp
    - [x] Test\testSmoothSegmentedFunctionFactory.cpp
    - [x] Test\testSTOFileAdapter.cpp
    - [x] Test\testStorage.cpp - #3557
    - [x] Test\testTRCFileAdapter.cpp
    - [x] Test\testXsensDataReader.cpp
- [x] Moco\
    - [x] Archive\Tests\test2Muscles1DOFDeGrooteFregly2016.cpp - #3562
    - [x] Archive\Tests\test2Muscles2DOFsDeGrooteFregly2016.cpp
    - [x] Archive\Tests\testGait10dof18musc.cpp
    - [x] Archive\Tests\testHangingMassRoundtrip.cpp
    - [x] Archive\Tests\testMultivariatePolynomial.cpp
    - [x] Archive\Tests\testSingleMuscle.cpp
    - [x] Archive\Tests\testSingleMuscleDeGrooteFregly2016.cpp
    - [x] Archive\Tests\testSingleMuscleDeGrooteFregly2016MomentArms.cpp
    - [x] Archive\Tests\testTugOfWarDeGrooteFregly2016.cpp
    - [x] Test\testMocoActuators.cpp - #3558
    - [x] Test\testMocoAnalytic.cpp
    - [x] Test\testMocoConstraints.cpp
    - [x] Test\testMocoContact.cpp
    - [x] Test\testMocoGoals.cpp
    - [x] Test\testMocoImplicit.cpp
    - [x] Test\testMocoInterface.cpp
    - [x] Test\testMocoInverse.cpp
    - [x] Test\testMocoMetabolics.cpp
    - [x] Test\testMocoParameters.cpp
    - [x] Test\testMocoTrack.cpp
- [x] Simulation\
    - [x] SimbodyEngine\Test\testConstraints.cpp
    - [x] SimbodyEngine\Test\testJoints.cpp
    - [x] Test\testAssemblySolver.cpp
    - [x] Test\testContactGeometry.cpp
    - [x] Test\testForces.cpp
    - [x] Test\testFrames.cpp
    - [x] Test\testInitState.cpp
    - [x] Test\testInverseKinematicsSolver.cpp
    - [x] Test\testManager.cpp (https://github.com/opensim-org/opensim-core/pull/4110)
    - [x] Test\testModelInterface.cpp (https://github.com/opensim-org/opensim-core/pull/4196)
    - [x] Test\testMomentArms.cpp (https://github.com/opensim-org/opensim-core/pull/4197)
    - [x] Test\testMuscleMetabolicsProbes.cpp (https://github.com/opensim-org/opensim-core/pull/4198)
    - [x] Test\testNestedModelComponents.cpp (https://github.com/opensim-org/opensim-core/pull/4199)
    - [x] Test\testPoints.cpp (https://github.com/opensim-org/opensim-core/pull/4200)
    - [x] Test\testPointToPointSpring.cpp
    - [x] Test\testPrescribedForce.cpp (https://github.com/opensim-org/opensim-core/pull/4202)
    - [x] Test\testProbes.cpp (https://github.com/opensim-org/opensim-core/pull/4203)
    - [x] Test\testReportersWithModel.cpp (https://github.com/opensim-org/opensim-core/pull/4204)
    - [x] Test\testSimulationUtilities.cpp (https://github.com/opensim-org/opensim-core/pull/4205)
    - [x] Test\testStatesTrajectory.cpp (https://github.com/opensim-org/opensim-core/pull/4206)
    - [x] Test\testTableProcessor.cpp
- [x] Tests\
    - [x] AddComponents\testAddComponents.cpp (https://github.com/opensim-org/opensim-core/pull/4213)
    - [x] Components\testComponents.cpp
    - [x] ConstantCurvatureExample\testConstantCurvature.cpp (https://github.com/opensim-org/opensim-core/pull/4214)
    - [x] ControllerExample\testControllerExample.cpp (https://github.com/opensim-org/opensim-core/pull/4215)
    - [x] CustomActuatorExample\testCustomActuatorExample.cpp (https://github.com/opensim-org/opensim-core/pull/4217)
    - [x] ExampleMain\testExampleMain.cpp (https://github.com/opensim-org/opensim-core/pull/4218)
    - [x] MuscleExample\testMuscleExample.cpp (https://github.com/opensim-org/opensim-core/pull/4219)
    - [x] OptimizationExample_Arm26\testOptimizationExample.cpp (https://github.com/opensim-org/opensim-core/pull/4220)
    - [x] ~~README\testREADME.cpp~~ (https://github.com/opensim-org/opensim-core/pull/4221)
    - [x] SimpleOptimizationExample\testSimpleOptimizationExample.cpp (https://github.com/opensim-org/opensim-core/pull/4222)
    - [x] testIterators\testIterators.cpp (https://github.com/opensim-org/opensim-core/pull/4223)
    - [x] testMemoryLeaks\testMemoryLeaks.cpp (https://github.com/opensim-org/opensim-core/pull/4107)
    - [x] Wrapping\testWrapCylinder.cpp (https://github.com/opensim-org/opensim-core/pull/4106)
    - [x] Wrapping\testWrapping.cpp
    - [x] Wrapping\testWrappingAlgorithm.cpp
    - [x] Wrapping\testWrapping_Deprecated.cpp
- [x] Tools\
    - [x] Test\testControllers.cpp
    - [x] Test\testExternalLoads.cpp
    - [x] Test\testModelCopy.cpp (https://github.com/opensim-org/opensim-core/pull/4208)
    - [x] Test\testSerializeOpenSimObjects.cpp (https://github.com/opensim-org/opensim-core/pull/4209)
    - [x] Test\testVisualization.cpp (https://github.com/opensim-org/opensim-core/pull/4210)
- [x] Vendors\ - #3580
    - [x] lepton\test\testLepton.cpp

**Comment by adamkewley** [comment]
List created with hacky script:

```python
import os
import itertools

srcdir = 'C:\\Users\\adamk\\Desktop\\opensim-core\\OpenSim'

all = []
for root, subdirs, files in os.walk(srcdir):
    for file in files:
        if file.lower().startswith('test') and file.lower().endswith('cpp'):
            p = os.path.relpath(os.path.join(root, file), srcdir)
            all.append(p)

for k, g in itertools.groupby(all, lambda el: el.split(os.path.sep)[0]):
    print(f'- [ ] {k}{os.path.sep}')
    for el in g:
        rest = os.path.sep.join(el.split(os.path.sep)[1:])
        print(f'    - [ ] {rest}')

```

**Comment by nickbianco** [comment]
@adamkewley I added some tests under `/Vendors` that your script missed.

**Comment by nickbianco** [comment]
Okay _now_ we're done with Phase 1 (converted all tests under `/Applications`.
