### ISSUE TITLE
Make use of Frames

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#369]
Frames were designed and implemented but nothing is using them. Below is a list of tasks to make good use of Frames and to help make the API easier to use and more robust.
Specific Tasks:
- [x] Replace use of a Body named "ground" with a Ground (Physical)Frame. Ground is an attribute of a Model (for now) but should belong to an Environment component when it exists. See #370
- [x] Enable Joints to connect to PhysicalFrames (which includes Ground and Bodies as well as PhysicalOffsets) addressed in #370
- [x] Scaling should be moved to PhysicalFrame (like Body)  addressed in #370
- [x] Rename methods and member variables to reflect the use of Frames instead of Bodies.
- [x] Eliminate `location/orientationInChild/Parent` properties and related methods from Joint since a PhysicalOffset can encapsulate any transform on another PhysicalFrame.
- [x] Eliminate adhoc use of `location/orientationInChild/Parent` properties throughout other Components, like Constraints (Weld, and other body to body constraints), Forces (e.g. Bushings, Springs, Contact), etc ...
- [ ] Both VisibleObject and the WrapObjectSet should NOT be properties of the PhysicalFrame. These properties should be their own components with Connectors to the Frames they attach to. This must be addressed prior to OpenSim 4.0 release

**Comment by chrisdembia** [comment]
+!

**Comment by msdemers** [comment]
so close to making my dreams come true!

**Comment by chrisdembia** [comment]
> Eliminate location/orientationInChild/Parent properties and related methods from Joint since a PhysicalOffset can encapsulate any transform on another PhysicalFrame.

An aside: I don't think we should delete the current constructors that take a location and orientation vec3, for backwards compatibility. (just add the new ones)

**Comment by aseth1** [comment]
@msdemers take a look at PR #370, perhaps part of your dream has come true already :smile:

**Comment by aseth1** [comment]
> An aside: I don't think we should delete the current constructors that take a location and orientation vec3, for backwards compatibility. (just add the new ones)

Sure. The current constructors could remain and be used to create the necessary Frames. Thanks!

**Comment by aseth1** [comment]
@chrisdembia @aymanhab I think it will be straightforward to map the location and orientation of Components to use of a PhysicalOffsetFrame with similar attributes. I will try that on the next pass.

**Comment by msdemers** [comment]
> take a look at PR #370, perhaps part of your dream has come true already

:smile_cat:

**Comment by chrisdembia** [comment]
Could we add a `Frame::findLocationInGround()` convenience method?

**Comment by chrisdembia** [comment]
Seems like PointKinematics needs to be updated too; see [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Analyses/PointKinematics.cpp#L168) for example.

**Comment by jenhicks** [comment]
@aseth1 Can you review the checklist and check off any items that are completed?

**Comment by chrisdembia** [comment]
Might need to rename ContactGeometry::getBody() -> ContactGeometry::getPhysicalFrame().
