### ISSUE TITLE
Remaining Hackathon TODO

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#838]
This issue does not include tasks related to the didactic example.

- [x] Reporter: @aseth1 hands off this afternoon to @chrisdembia @klshrinidhi (PR #843)
- [x] Outputs for certain components: @aymanhab (PR #796)
- [x] Outputs for return by `const T&`: @chrisdembia @aymanhab (PR #839)
- [ ] TableSource: @klshrinidhi 
- [x] Adapter wrapping: @klshrinidhi 
- [ ] Wrapping ComponentList, Output, Input: @chrisdembia @aymanhab 
- [ ] PR StatesCollector review @aseth1 @klshrinidhi 
- [ ] PR StatesTrajectory export to DataTable @aseth1 @klshrinidhi 
- [ ] Simulator class: @aseth1 
- [ ] GUI build: @aymanhab (btw you can use AppVeyor's automated build).
- [ ] Adding Components to ModelComponents @aseth1

**Comment by chrisdembia** [comment]
Adding an item above: allowing an easy way to add Components to a Model (Models can only contain ModelComponents).

**Comment by aymanhab** [comment]
@chrisdembia Do you have a branch for item 5 above (Wrapping lists) that we discussed yesterday? Would be good to get  PR #858 in first so we can try some examples. Tests still running.

**Comment by chrisdembia** [comment]
> @chrisdembia Do you have a branch for item 5 above (Wrapping lists) that we discussed yesterday?

I'm going to work on it later today.

**Comment by chrisdembia** [comment]
@aymanhab with regard to wrapping component lists, outputs, inputs, what's of the highest priority for you? Especially given @jenhicks's reminder that people aren't necessarily using wrapping for their hackathon projects? I still plan to work on wrapping, but perhaps just not as completely.

**Comment by aymanhab** [comment]
@chrisdembia I wanted first to rename the methods per our conversations (BodiesList to BodyList etc.), add test case to exercise them, and then try to show output list in the GUI for the hackathon, which will in theory make it possible to use outputs in Python/Java/Matlab. Just wasn't sure if you started down this road of implementing the plan/doc we discussed yesterday.

**Comment by chrisdembia** [comment]
I have not started down the road yet.

**Comment by chrisdembia** [comment]
Well, sorry, yes I have started, but I'm not ready to show anything. Please just go ahead.

**Comment by chrisdembia** [comment]
I don't think I'm going to be able to submit anything about the wrapping in time for the hackathon.

**Comment by chrisdembia** [comment]
I got luxo to jump with the device! I didn’t change the luxo actuators, but I decreased their activation duration from 1.0 to 0.2 seconds. I also use *both* the device locations — that is, two devices on the luxo. I also decreased the mass of the device, since the device was previously 2x heavier than Luxo.

I’ll send a screenshot in a followup email. I’m having trouble pushing my code changes to GitHub because the wifi on the bus is pretty bad (couldn't even send an email).

The only problem to be solved is how to use the muscle’s control signal to drive the devices (right now my hack is to drive the device separately but with the same exact piecewise function as the muscles). As I mentioned, before, this is complicated for RigidTendonMuscles, and I don’t have time to explore solutions. The possibilities are:

1. Use a muscle with activation dynamics.

2. Use a Measure::Delay to create a delayed version of the muscle’s excitation, this would be available at Stage::Model.

3. Use the new ActivationDynamics subcomponent (that is currently being used in the Thelen muscle) with the RigidTendon muscle.

4. Use a cache variable to save the muscle’s activation?? Or an auto update discrete variable? Or one of those kinds of things.
